# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python 3.8 test action

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        make test
    - name: Flake8 test
      run: |
        make flake8

    - name: Generate example images
      run: |
        python print_box_label.py --no-backend --no-printer 1000
        ( echo "y" && echo "y" && echo ) | python print_warning_label.py --no-printer
    - name: Upload image artifacts
      uses: actions/upload-artifact@v2
      with:
        name: generated-images
        path: |
          *.png
